### ISSUE TITLE
Api: Produtos de todas categorias num arquivo só

### ISSUE THREAD

**Issue by rg3915** [rg3915/vendas#33]
@patymori Repare que na linha a seguir

https://github.com/rg3915/vendas/blob/master/vendas/api/get_produtos.py#L20

ele pega os produtos de cada categoria e cria um arquivo `produtos1.csv` até `produtos28.csv`.

Eu queria que salvasse todos os produtos de todas as categorias dentro de um arquivo só `produtos.csv`.

**Comment by patymori** [comment]
Quer eu eu coloque o `ID` e o `NOME` das categorias como coluna em `produtos.csv` ou só um deles?
